#!/bin/bash
#python evaluate.py data/subj26/ >> angular_diff/subj26_.txt
#python evaluate.py data/subj27/ >> angular_diff/subj27_.txt
#python evaluate.py data/subj28/ >> angular_diff/subj28_.txt
#python evaluate.py data/subj31/ >> angular_diff/subj31_.txt
#python evaluate.py data/subj32/ >> angular_diff/subj32_.txt
#python evaluate.py data/subj33/ >> angular_diff/subj33_.txt
#python evaluate.py data/subj34/ >> angular_diff/subj34_.txt
#python evaluate.py data/subj35/ >> angular_diff/subj35_.txt
#python evaluate.py data/subj36/ >> angular_diff/subj36_.txt
#python evaluate.py data/subj37/ >> angular_diff/subj37_.txt
#python evaluate.py data/subj38/ >> angular_diff/subj38_.txt
#python evaluate.py data/subj39/ >> angular_diff/subj39_.txt
#python evaluate.py data/subj42/ >> angular_diff/subj42_.txt
#python evaluate.py data/subj43/ >> angular_diff/subj43_.txt
#python evaluate.py data/subj44/ >> angular_diff/subj44_.txt
#python evaluate.py data/subj45/ >> angular_diff/subj45_.txt
#python evaluate.py data/subj46/ >> angular_diff/subj46_.txt
#python evaluate.py data/subj47/ >> angular_diff/subj47_.txt
#python evaluate.py data/subj48/ >> angular_diff/subj48_.txt
#python evaluate.py data/subj54/ >> angular_diff/subj54_.txt
#python evaluate.py data/subj56/ >> angular_diff/subj56_.txt
#python evaluate.py data/subj59/ >> angular_diff/subj59_.txt
#python evaluate.py data/subj61/ >> angular_diff/subj61_.txt
python evaluate.py data/subj63/ >> angular_diff/subj63_.txt
#python evaluate.py data/subj64/ >> angular_diff/subj64_.txt
