# environment parameters
SIZE = 100 # 10 
ROOM_X = 8.534 * SIZE
ROOM_Z = 7.315 * SIZE
OFF_X = ROOM_X/2
OFF_Z = ROOM_Z/2
TAR_SIZE = 0.1829 * SIZE
OBS_SIZE = 0.2896 / 2 * SIZE
AGENT_SIZE = 0.03 * SIZE
CELL = 5 # state granularity
FONT_SIZE = SIZE / 10 
SHOW_GRID = False
DISCRETE = False

# actions
STAY = 0; 
LEFT = 1; UPLEFT = 2; UP = 3; UPRIGHT = 4
RIGHT = 5; DOWNRIGHT = 6; DOWN = 7; DOWNLEFT = 8
ACTIONS = [STAY, LEFT, UPLEFT, UP, UPRIGHT, RIGHT, DOWNRIGHT, DOWN, DOWNLEFT]
ACT_NAMES = ["STAY", "LEFT", "UPLEFT", "UP", "UPRIGHT", "RIGHT", "DOWNRIGHT", "DOWN", "DOWNLEFT"]

