#!/bin/bash
#./build_data_subj.sh 26
#./build_data_subj.sh 27
#./build_data_subj.sh 28
#./build_data_subj.sh 31
#./build_data_subj.sh 32
#./build_data_subj.sh 33
#./build_data_subj.sh 34
#./build_data_subj.sh 35
#./build_data_subj.sh 36
#./build_data_subj.sh 37
#./build_data_subj.sh 38
#./build_data_subj.sh 39
#./build_data_subj.sh 42
#./build_data_subj.sh 43
#./build_data_subj.sh 44
#./build_data_subj.sh 45
#./build_data_subj.sh 46
#./build_data_subj.sh 47
#./build_data_subj.sh 48
#./build_data_subj.sh 54
#./build_data_subj.sh 56
#./build_data_subj.sh 59
#./build_data_subj.sh 61
#./build_data_subj.sh 63
#./build_data_subj.sh 64
./run_irl.sh 26
./run_irl.sh 27
./run_irl.sh 28
./run_irl.sh 31
./run_irl.sh 32
./run_irl.sh 33
./run_irl.sh 34
./run_irl.sh 35
./run_irl.sh 36
./run_irl.sh 37
./run_irl.sh 38
./run_irl.sh 39
./run_irl.sh 42
./run_irl.sh 43
./run_irl.sh 44
./run_irl.sh 45
./run_irl.sh 46
./run_irl.sh 47
./run_irl.sh 48
./run_irl.sh 54
./run_irl.sh 56
./run_irl.sh 59
./run_irl.sh 61
./run_irl.sh 63
./run_irl.sh 64
