#!/bin/bash
./build_data_subj.sh 37
./run_irl.sh 37
./build_data_subj.sh 38
./run_irl.sh 38
./build_data_subj.sh 39
./run_irl.sh 39
./build_data_subj.sh 43
./run_irl.sh 43
./build_data_subj.sh 44
./run_irl.sh 44
./build_data_subj.sh 45
./run_irl.sh 45
./build_data_subj.sh 46
./run_irl.sh 46
./build_data_subj.sh 47
./run_irl.sh 47
./build_data_subj.sh 48
./run_irl.sh 48
./build_data_subj.sh 54
./run_irl.sh 54
./build_data_subj.sh 56
./run_irl.sh 56
./build_data_subj.sh 59
./run_irl.sh 59
./build_data_subj.sh 61
./run_irl.sh 61
./build_data_subj.sh 63
./run_irl.sh 63
./build_data_subj.sh 64
./run_irl.sh 64
